2017-06-19 10:26:22,522 [INFO] from play.core.server.NettyServer in pool-4-thread-3 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2017-06-19 10:27:15,200 [WARN] from application in ForkJoinPool-1-worker-1 - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2017-06-19 10:27:17,212 [WARN] from application in ForkJoinPool-1-worker-1 - application.langs is deprecated, use play.i18n.langs instead
2017-06-19 10:27:18,415 [INFO] from play.api.Play in ForkJoinPool-1-worker-1 - Application started (Dev)
2017-06-19 10:33:15,146 [WARN] from application in application-akka.actor.default-dispatcher-6 - application.conf @ file:/F:/3.UJ(LICENCJAT)/SEMESTR%20VIII/Ebiznes/movie/target/scala-2.11/classes/application.conf: 8: application.secret is deprecated, use play.crypto.secret instead
2017-06-19 10:50:59,013 [ERROR] from application in application-akka.actor.default-dispatcher-44 - 

! @74ck220cf - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:50:59,506 [ERROR] from application in application-akka.actor.default-dispatcher-44 - 

! @74ck22163 - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:50:59,890 [ERROR] from application in application-akka.actor.default-dispatcher-44 - 

! @74ck221kn - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:51:00,017 [ERROR] from application in application-akka.actor.default-dispatcher-44 - 

! @74ck221pk - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:51:17,117 [ERROR] from application in application-akka.actor.default-dispatcher-38 - 

! @74ck2317c - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:51:17,493 [ERROR] from application in application-akka.actor.default-dispatcher-38 - 

! @74ck231lo - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:51:18,037 [ERROR] from application in application-akka.actor.default-dispatcher-38 - 

! @74ck232gm - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:51:18,333 [ERROR] from application in application-akka.actor.default-dispatcher-38 - 

! @74ck23326 - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 10:51:18,501 [ERROR] from application in application-akka.actor.default-dispatcher-47 - 

! @74ck2338i - Internal server error, for (POST) [/api/cart/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((/idUser,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:23)
	at controllers.CartController$$anonfun$apiNewCart$1.apply(CartController.scala:21)
	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2017-06-19 11:42:33,728 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-84 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:49:58,223 [WARN] from application in application-akka.actor.default-dispatcher-78 - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2017-06-19 11:49:58,525 [WARN] from application in application-akka.actor.default-dispatcher-78 - application.langs is deprecated, use play.i18n.langs instead
2017-06-19 11:49:58,692 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-78 - Application started (Dev)
2017-06-19 11:50:02,564 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-2 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:50:31,167 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-10 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:50:44,390 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-3 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:52:29,011 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-13 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:52:44,052 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-10 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:53:58,909 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-14 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 11:57:26,378 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-16 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:00:48,186 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-17 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:01:08,599 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-18 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:01:30,654 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-18 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:02:08,449 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-19 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:03:13,965 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-23 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:03:17,631 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-24 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:03:33,255 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:06:41,285 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-26 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.ProfileRetrievalException: [Silhouette][google] Error retrieving profile information. Error code: 403, message: Project 1020543940463 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1020543940463 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth2.BaseGoogleProvider$$anonfun$buildProfile$1.apply(GoogleProvider.scala:63)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:39:21,117 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-28 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:39:22,821 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-28 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:164)
	at scala.util.Either.fold(Either.scala:98)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:163)
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:121)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:152)
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-06-19 12:39:34,292 [WARN] from application in application-akka.actor.default-dispatcher-29 - application.conf @ file:/F:/3.UJ(LICENCJAT)/SEMESTR%20VIII/Ebiznes/movie/target/scala-2.11/classes/application.conf: 8: application.secret is deprecated, use play.crypto.secret instead
2017-06-19 13:26:54,468 [WARN] from application in application-akka.actor.default-dispatcher-32 - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2017-06-19 13:26:54,739 [WARN] from application in application-akka.actor.default-dispatcher-32 - application.langs is deprecated, use play.i18n.langs instead
2017-06-19 13:26:54,855 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-32 - Application started (Dev)
2017-06-19 13:27:46,205 [WARN] from org.apache.http.impl.client.DefaultHttpClient in ForkJoinPool-1-worker-0 - Authentication error: Unable to respond to any of these challenges: {oauth=www-authenticate: OAuth realm="https://twitter.com"}
2017-06-19 13:27:46,214 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-8 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][twitter] Error retrieving request token
	at com.mohiva.play.silhouette.impl.providers.OAuth1Provider$$anonfun$authenticate$1.applyOrElse(OAuth1Provider.scala:101)
	at com.mohiva.play.silhouette.impl.providers.OAuth1Provider$$anonfun$authenticate$1.applyOrElse(OAuth1Provider.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
	at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:243)
	at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
	at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74)
	at play.api.libs.oauth.OAuth.retrieveRequestToken(OAuth.scala:36)
	at com.mohiva.play.silhouette.impl.providers.oauth1.services.PlayOAuth1Service$$anonfun$retrieveRequestToken$1.apply(PlayOAuth1Service.scala:70)
	at com.mohiva.play.silhouette.impl.providers.oauth1.services.PlayOAuth1Service$$anonfun$retrieveRequestToken$1.apply(PlayOAuth1Service.scala:70)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	... 5 common frames omitted
2017-06-19 14:55:01,146 [WARN] from application in application-akka.actor.default-dispatcher-13 - application.conf @ file:/F:/3.UJ(LICENCJAT)/SEMESTR%20VIII/Ebiznes/movie/target/scala-2.11/classes/application.conf: 8: application.secret is deprecated, use play.crypto.secret instead
